export const projects = [
  {
    title: 'OC Academy',
    description: "This is a fully functional web application developed for a Canadian company. User can explore different courses and programs offered by the institute and purchase directly from the site. I was the the team lead of the project.",
    image: '/images/img-oca.PNG',
    tags: ['Express', 'Node', 'GraphQL', 'MongoDB', 'Vue','Nuxt','Stripe'],
    isPrivate: true,
    link: 'https://ocacademy.ca',
    code: '',
    id: 0,
  },
  {
    title: 'Lighthouse Academy',
    description: "This is a Canadian online school course management system. Using this web application, students can register for courses of grade 9 to 12. This system allows payment for the registration, automatic invoice generation, automatic mailing etc.",
    image: '/images/img-lha.PNG',
    tags: ['Express', 'Node', 'GraphQL', 'MongoDB', 'Vue','Nuxt','Stripe'],
    isPrivate: true,
    link: 'https://course.lighthouseacademy.ca',
    code: '',
    id: 1,
  },
  {
    title: 'Vid Quiz',
    description: "This is a video based quiz web application where participants can watch videos on certain topics and then participate in quiz, see the result. Authentication has been implemented in this application using firebase.",
    image: '/images/img-vid-quiz.PNG',
    tags: ['React','Next','TypeScript','Prisma','MongoDB','Material UI'],
    isPrivate:false,
    link: 'https://car-mart.vercel.app',
    code: 'https://github.com/devshafi/car-mart',
    id: 2,
  },
  {
    title: 'Car Mart',
    description: "This is a demo project where the main focus was implementing SEO friendly queries, SSR, SSG etc. using Next.JS and TypeScript",
    image: '/images/img-car-mart.PNG',
    tags: ['React','Next','TypeScript','Prisma','MongoDB','Material UI'],
    isPrivate:false,
    link: 'https://car-mart.vercel.app',
    code: 'https://github.com/devshafi/car-mart',
    id: 3,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];